### ISSUE TITLE
Advocate offering support

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphadvocates/members#3]
Hey @Web3Slimchance,

Just posting here to say I'd like to support this member profile project.

Let me know if you need any support with this GitHub repo or wrangling/normalizing data from advocates.

Best,
Pakaliscious

**Comment by Web3Slimchance** [comment]
Hi @alex-pakalniskis 
Thanks for offering. There is now a `#dao-member-profiles` channel in Discord. The channel was created to provide technical support on creating public member profiles. (Note: The pinned post have a tutorial for creating member profiles)

If you can help keep an eye on that channel, it would be very much appreciated. Let me know if you want to help with reviewing the PRs as well.

**Comment by alex-pakalniskis** [comment]
@Web3Slimchance I'll definitely keep an eye on the Discord channel. Likewise I'm happy to help review PRs.

**Comment by Web3Slimchance** [comment]
Thank you. I will add you to the repo. 🙌
